cmd: "/home/hmg/miniconda3/envs/covid-main/bin/python"
name: "Build entire project"
args:
  - waf.py
  - configure
  - build
  - install
sh: true,
cwd: /home/hmg/econ/covid-19-impact-lab/presentations
env:
  PATH: "/home/hmg/miniconda3/envs/covid-main/bin:/home/hmg/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/hmg/econ/texlive/2019/bin/x86_64-linux:/usr/local/stata14:.:/usr/local/julia/bin"
  WAFLOCK: ".lock-wafbld"
errorMatch:
  - ^regexp1$
  - ^regexp2$
warningMatch:
  - ^regexp1$
  - ^regexp2$
